# If path or main is empty ("") default is going to be used
# File's name that needs to be served (defaults to index.html)
main: ""
# If you want custom error 404 page put a 404.html file in the same directory as the other html file
# Path where the html can be found (defaults to the same directory where the launcher is found)
path: ""
# Port number is needed, there is no default yet. Might support it later.
port: 7878